version: 2

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell

linters-settings:
  gosec:
    config:
      G304: "0"  # Disable file path variable check
      G204: "0"  # Disable subprocess variable check
      G301: "0"  # Disable directory permissions check
      G306: "0"  # Disable file permissions check

issues:
  exclude-use-default: true
  exclude-rules:
    # Exclude all gosec warnings in test files
    - path: _test\.go
      linters:
        - gosec
    # Exclude revive warnings for package comments
    - linters:
        - revive
      text: "package-comments"
    # Exclude revive warnings for exported comments
    - linters:
        - revive
      text: "exported"
    # Exclude revive warnings for unused parameters
    - linters:
        - revive
      text: "unused-parameter"
  max-issues-per-linter: 0
  max-same-issues: 0
